services:
  database:
    image: 'postgres:16.9'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - ./data:/var/lib/postgresql/data
